### ISSUE TITLE
Make ajax request for schema URI relative to server root.

### ISSUE THREAD

**Issue by whikloj** [UNC-Libraries/jquery.xmleditor#33]
I am working on trying to embed your wonderful XML editor inside of a Drupal module. 

It appears that when requesting the schema document it is always relative to the Url of the directory the page is inside. So when loading your editor for a new page in Drupal I start at:
**http://localhost/node/add/basic-page**

This means the Ajax request is sent to:
**http://localhost/node/add/&lt;schema file&gt;**

Which makes it hard to use within the context of the Drupal menu system. It would be easier if I could strip it back to the hostname and append the address there.

I forked and made some changes [to show what I would propose here](https://github.com/UNC-Libraries/jquery.xmleditor/compare/master...whikloj:islandora-changes?expand=1). 

I'm certain there are better ways to do this, but you can get the picture of what I am doing.

**Comment by bbpennel** [comment]
Thanks for your interest, I agree with your suggestion.  

My first thought is that it is useful to allow for locations which are relative to the current page's URL.  So I would like to allow for the following three options:

"path/to/<schema file>" - relative to the current folder
"/path/to/<schema file>" - relative to the base of the server
"http://domain/path/to/<schema file>" - absolute path

Preferably this would all be done through the existing this.options.schema value rather than through a new property.

I am thinking something like the following would cover all three cases and work for you?
```javascript
			if ($.type(this.options.schema) =='string') {
				if (absRegExp.test(this.options.schema)) {
					// Absolute path, use as is
				} else if (this.options.schema.indexOf('/') == 0) {
					// Relative to root
					var matches = this.baseUrl.match(absRegExp);
					this.options.schema = matches[0] + '/' + this.options.schema;
				} else {
					// Relative to current path
					this.options.schema = this.baseUrl + this.options.schema;
				}
			}
```

The setting of libPath would probably need to be updated accordingly

**Comment by whikloj** [comment]
That sounds good to me, and I agree that the libPath would also need to be adjusted.

Thanks.

**Comment by lfarrell** [comment]
This feature has been added to the master branch now.
