### ISSUE TITLE
How to use namespace with CSS

### ISSUE THREAD

**Issue by TueHenriksen** [UNC-Libraries/jquery.xmleditor#38]
Hi

I am trying to write some CSS to customize the look so different elements have different formatting. In my xsd-file I could have <xs:element name="fish" type="xs:string"/>.

In the XML editor I can see that the <div> section containing <fish> belongs to the following classes:

class="4_fishInstance xml_element top_level_element_group"

After some debugging I have found out that "4" is a namespace. Since I am not allowed to use leading numbers in CSS, I would like to know how I could set this namespace to something meaningful (a string containing letters).

Anyway, thanks for a great tool.

/Tue

**Comment by bbpennel** [comment]
Thanks for trying the editor out!  Yes, you are correct, it prefixes by namespace index.  That happens here https://github.com/UNC-Libraries/jquery.xmleditor/blob/master/src/xml_element.js#L62.  You can see an example of getting a namespace prefix here https://github.com/UNC-Libraries/jquery.xmleditor/blob/master/src/xml_element.js#L92.  Changing the class name would be fairly straightforward, and likely wouldn't effect other functionality.  So if you are interested in doing this, it could potentially be useful, it wasn't an intentional decision making the class something that css couldn't be applied to.

**Comment by lfarrell** [comment]
@TueHenriksen This issue should be fixed now in the master branch. I ended up flipping the namespace id and the localName to derive a valid CSS class.

**Comment by TueHenriksen** [comment]
Thanks a lot... However, I would still prefer if the name of the namespace was used instead of just an index. But now it is accessible from CSS :-)
