### ISSUE TITLE
Search & Find in 'Text' mode

### ISSUE THREAD

**Issue by RivkaTalalai** [UNC-Libraries/jquery.xmleditor#60]
When using the browser's search (CTRL+ F) I find expressions that are visible but not expressions that require scrolling because the elements are generated on the fly after scrolling and do not exist on the page before hand. 

This is a pain point when working with large files.

Is there a way around this problem?  (I noticed that CTRL + A does manage to retrieve everything, including 'hidden' text..)

Thanks in advance!

**Comment by bbpennel** [comment]
Hi Rivka.  You should be able to resolve this without making any code changes since the "text" mode is built on top of the Ace editor.  There is an extension for the editor which adds a search box when the users hits ctrl+f which will find strings that are off the page.  If you import this extension on the page where you are using the XML editor, you will get the search box:

https://github.com/ajaxorg/ace-builds/blob/master/src-min/ext-searchbox.js

This is a pretty standard feature though, so I think it would make sense to include it in the suggested configuration.

**Comment by rosetta-development** [comment]
That did the trick!
Thank you so much!
