### ISSUE TITLE
Add widget method to retrieve current XML string

### ISSUE THREAD

**Issue by vog** [UNC-Libraries/jquery.xmleditor#76]
The provided menu entries for "Export" and "Upload" do not cover all use cases. It would be great if the surrounding code could request the current XML value from the editor, similar to what we are used to with text fields, text areas and all other kinds of input fields.

Which method name is appropriate?

```js
var xmlString = $('#xml-editor').xmlEditor('xml');
var xmlString = $('#xml-editor').xmlEditor('xmlString');
var xmlString = $('#xml-editor').xmlEditor('getXml');
var xmlString = $('#xml-editor').xmlEditor('getXmlString');
var xmlString = $('#xml-editor').xmlEditor('val');
var xmlString = $('#xml-editor').xmlEditor('value');
var xmlString = $('#xml-editor').xmlEditor('getValue');
```

Which behaviour is appropriate if the xmlEditor is in Text mode rather than XML mode?

1. Return the latest XML mode value, i.e. ignore everything that happened in Text mode. (very fast, but perhaps too simple-minded)
2. Return the current Text mode value if it is valid, otherwise return the latest XML mode value. (might be computationally intensive)
3. Return the current Text mode value if it is valid, otherwise return the latest valid Text mode value. (may result in surprising hehaviour for the user)
4. Return the current Text mode value if it is valid, otherwise return `null`. (might be computationally intensive)
5. Return the current Text mode value if it is valid, otherwise throw an exception. (not recommended - a getter should not throw an exception)

@bbpennel Any opinions?

**Comment by bbpennel** [comment]
I would say `$('#xml-editor').xmlEditor('getXmlString')` since the behavior is a getter rather than an attribute or action.  `getValue` would be okay too, but seems more ambiguous.

In terms of behavior, my preference would be towards option 2.  It seems like the most expected behavior for a `getXmlString` method.  If this method needs to be called frequently enough that the performance will be an issue we could provide either additional getters or flags to the method that allowed for option 1.  I could see users also wanting another option that returned the current value from the text mode whether it is valid or not.

**Comment by vog** [comment]
Option 2 is fine for me, too, so let's stick with that.

**Comment by vog** [comment]
According to the general naming conventions within `jquery.xmleditor`, `getXMLString` is better than `getXmlString`.

**Comment by vog** [comment]
Implemented the method. Not sure where to add it to the docs, so I'll leave it like that.
