### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by vog** [UNC-Libraries/jquery.xmleditor#78]
As discussed in #72, we do need unit tests.

**Comment by bbpennel** [comment]
Thanks so much for doing this, @vog!  One thing I'm curious about is if you feel it is preferable to use the small custom framework you added versus an existing one?  Wasn't sure if it was a engineering decision or you not wanting to make a decision like that for a project you were contributing to.

It seems like these tests are closer to being integration tests of xsd2json than unit tests since they are dealing with the completed output of the module versus the individual units that make it up.  Not that I'm complaining.  

I am wondering though if we should namespace the tests some since these are very specific to testing the xsd2json component in a specific way (xsd in, json out).

**Comment by vog** [comment]
Feel free to switch to any JS unit testing framework as you see fit. The minimal hand-written "framework" was just a vehicle it get it running as quickly as possible. Most effort went into collecting the test data and writing the test cases, not in the "framework" itself.

Regarding the directory structure, I would prefer to have all tests of the whole project in a single place, but ultimately I would do whatever the convention of the chosen framework is.

**Comment by vog** [comment]
Two more notes on this:

The test cases contain the example schemas (atom, mods, dcterms) and the expected output JSON were created with version 51df56f6aa1575b675e4cf318ba770aa7ee4fefd, that is, before any of my changes. After my changes, these test cases are still unchanged, so I'm sure I didn't introduce any bugs on them. Of course, the other test cases added by myself did need to be changed on the way, as these explored exactly the corner cases that the old version didn't handle correctly.

I won't put any more work into the tests, apart from adding more tests as I find new issues. It would be great if you could "take over" the test framework stuff, I just wanted to get this up and running, because the fix for #80 and the upcoming fixes would not have been possible in reasonable time without unit testing on the way.

**Comment by bbpennel** [comment]
Okay, this is a good starting point for getting unit tests in, and can be refactored later to use a different framework if need be.  The test cases so far should carry over well enough regardless, and in the meantime it will be much easier to verify and debug the issues you are working on.  Thanks again for your work on this @vog
